AWSTemplateFormatVersion: 2010-09-09
Description: Gilberto Trevino / Udacity - This template deploys servers resources.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket where the static website is hosted
    Value: !Join ['', ['s3://', !Ref S3Bucket]]

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${EnvironmentName}-project2-storage

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3BucketPolicy
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]